#!/usr/bin/env node
// Generates the self-contained JSON schemas of the formats from their sources in src/schemas/.
//
// usage:
//   node scripts/schemas.ts build [srcDir] [outDir]  generates the schemas (default: dist/schemas)
//   node scripts/schemas.ts check [srcDir]           validates the sources, exits with 1 on a problem
//
// The sources are the canonical files: src/schemas/_defs.json holds the shared $defs (uint8, float32,
// vector3, ...) and src/schemas/<format>.schema.json only defines what is local to that format. A published
// schema has to be self-contained (every "#/$defs/x" $ref resolves inside the same file), so this script
// injects the shared defs a format schema references - transitively, in the order of _defs.json.
//
// Every generated schema is stamped with "x-generatedBy" (the name@version of this package), so a published
// copy can be traced back to the release which generated it.
//
// The output is a build artifact in dist/ (git ignored, never committed, never edited by hand), so the
// generated schemas and their sources can not drift apart: there is no sync step, a build always writes them
// from scratch.
// This file only uses erasable TypeScript syntax so that node.js can run it with type stripping.
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'

const DEFAULT_SRC_DIR = 'src/schemas'
const DEFAULT_OUT_DIR = 'dist/schemas'
// the shared defs; the leading underscore marks the file which is not a format schema
const DEFS_FILENAME = '_defs.json'
const PACKAGE_FILENAME = 'package.json'
const REF_PREFIX = '#/$defs/'
// the "generated by" annotation written into the generated schemas
const GENERATED_BY_KEY = 'x-generatedBy'
// the keys of the generated schema in the order they should appear, every other key follows them
const KEY_ORDER = ['$schema', '$id', 'title', 'description', GENERATED_BY_KEY, '$defs']

type JsonObject = Record<string, unknown>

function isObject(value: unknown): value is JsonObject {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

async function loadJson(filename: string): Promise<JsonObject> {
  return JSON.parse(await readFile(filename, 'utf8')) as JsonObject
}

/**
 * Collects every "#/$defs/name" reference name found in the given JSON value.
 */
function collectRefNames(value: unknown, refNames: Set<string> = new Set<string>()): Set<string> {
  if (Array.isArray(value)) {
    for (const item of value) {
      collectRefNames(item, refNames)
    }
  } else if (isObject(value)) {
    for (const [key, child] of Object.entries(value)) {
      if (key === '$ref' && typeof child === 'string' && child.startsWith(REF_PREFIX)) {
        refNames.add(child.slice(REF_PREFIX.length))
      } else {
        collectRefNames(child, refNames)
      }
    }
  }

  return refNames
}

/**
 * The names of the shared defs a format schema needs: the referenced shared defs plus every
 * shared def they themselves reference (for example `color` references `uint8`).
 */
function requiredSharedDefs(referencedNames: Set<string>, canonicalDefs: JsonObject): Set<string> {
  const required = new Set<string>()

  function visit(name: string): void {
    if (required.has(name)) {
      return
    }

    required.add(name)

    for (const ref of collectRefNames(canonicalDefs[name])) {
      if (ref in canonicalDefs) {
        visit(ref)
      }
    }
  }

  for (const name of referencedNames) {
    if (name in canonicalDefs) {
      visit(name)
    }
  }

  return required
}

/**
 * Reorders the keys of the schema so the generated file always looks the same: the metadata and the $defs
 * first (that is what a reader looks for), the format specific keywords after them.
 */
function orderKeys(doc: JsonObject): JsonObject {
  const ordered: JsonObject = {}

  for (const key of KEY_ORDER) {
    if (key in doc) {
      ordered[key] = doc[key]
    }
  }

  for (const [key, value] of Object.entries(doc)) {
    if (!(key in ordered)) {
      ordered[key] = value
    }
  }

  return ordered
}

/**
 * Returns a copy of the format schema with the shared defs it references injected, so the result is
 * self-contained, and stamped with the arx-convert release it was generated by. The local defs are kept in
 * their source order, the shared ones follow in the order of _defs.json. Throws an Error when the source
 * defines a shared def locally, or references a def which is neither defined locally nor shared.
 *
 * @example
 * generateSchema(JSON.parse(await readFile('src/schemas/fts.schema.json', 'utf8')), defs, 'arx-convert@1.2.3')
 */
function generateSchema(doc: JsonObject, canonicalDefs: JsonObject, generatedBy: string): JsonObject {
  let sourceDefs: JsonObject
  if (isObject(doc.$defs)) {
    sourceDefs = doc.$defs
  } else {
    sourceDefs = {}
  }

  for (const name of Object.keys(sourceDefs)) {
    if (name in canonicalDefs) {
      throw new Error(
        `"${name}" is a shared definition of _defs.json - a format schema only defines what is local to the format, the shared definitions are injected by the build`,
      )
    }
  }

  const required = requiredSharedDefs(collectRefNames(doc), canonicalDefs)
  const newDefs: JsonObject = { ...sourceDefs }
  for (const name of Object.keys(canonicalDefs)) {
    if (required.has(name)) {
      newDefs[name] = structuredClone(canonicalDefs[name])
    }
  }

  const newDoc: JsonObject = { ...doc, [GENERATED_BY_KEY]: generatedBy }
  if (Object.keys(newDefs).length > 0) {
    newDoc.$defs = newDefs
  } else {
    delete newDoc.$defs
  }

  for (const ref of collectRefNames(newDoc)) {
    if (!(ref in newDefs)) {
      throw new Error(
        `"#/$defs/${ref}" is referenced, but it is not defined in this file nor in _defs.json. If it's only defined in another format schema and you want to share it, move it into _defs.json`,
      )
    }
  }

  return orderKeys(newDoc)
}

// ---------------------------------

const [command, srcDirArg, outDirArg] = process.argv.slice(2)
if (command !== 'build' && command !== 'check') {
  console.error('usage: node scripts/schemas.ts <build|check> [srcDir] [outDir]')
  process.exit(1)
}

const srcDir = path.resolve(srcDirArg ?? DEFAULT_SRC_DIR)
const outDir = path.resolve(outDirArg ?? DEFAULT_OUT_DIR)
const defsDoc = await loadJson(path.join(srcDir, DEFS_FILENAME))

const canonicalDefsValue = defsDoc.$defs
if (!isObject(canonicalDefsValue) || Object.keys(canonicalDefsValue).length === 0) {
  console.error(`"${DEFS_FILENAME}" has no $defs`)
  process.exit(1)
}

const canonicalDefs = canonicalDefsValue

// _defs.json has to be self-contained
for (const [name, def] of Object.entries(canonicalDefs)) {
  for (const ref of collectRefNames(def)) {
    if (!(ref in canonicalDefs)) {
      console.error(
        `"${DEFS_FILENAME}": "${name}" references "#/$defs/${ref}", which is not defined in ${DEFS_FILENAME}`,
      )
      process.exit(1)
    }
  }
}

// the generated schemas carry the release which generated them, so a published copy can be traced back
const packageJson = await loadJson(PACKAGE_FILENAME)
const generatedBy = `${packageJson.name as string}@${packageJson.version as string}`

const schemaFilenames = await readdir(srcDir)
const schemaFiles = schemaFilenames
  .filter((filename) => {
    return filename.endsWith('.schema.json')
  })
  .sort()

if (schemaFiles.length === 0) {
  console.error(`no *.schema.json files found in "${srcDir}"`)
  process.exit(1)
}

const generated: Array<{ filename: string; doc: JsonObject }> = []
let hadErrors = false

for (const filename of schemaFiles) {
  const doc = await loadJson(path.join(srcDir, filename))

  try {
    generated.push({ filename, doc: generateSchema(doc, canonicalDefs, generatedBy) })
  } catch (error) {
    console.error(`${filename}: ${(error as Error).message}`)
    hadErrors = true
  }
}

if (hadErrors) {
  console.error('the schemas could not be generated, see the errors above')
  process.exit(1)
}

if (command === 'check') {
  console.log(`all ${schemaFiles.length} schema sources are valid`)
} else {
  await mkdir(outDir, { recursive: true })
  for (const { filename, doc } of generated) {
    await writeFile(path.join(outDir, filename), `${JSON.stringify(doc, null, 2)}\n`)
  }

  console.log(`generated ${generated.length} schemas into "${outDirArg ?? DEFAULT_OUT_DIR}"`)
}
